# ======================================================================
# 06_figures_supplementary_fungi.R
# Purpose:
#   Generate supplementary figures for culturable fungi:
#   - Fig S4: Isolation success (N) vs alpha diversity (Richness, Shannon)
#   - Fig S5: Alpha diversity across organs, faceted by Management
#   - Fig S6: PCoA (Bray–Curtis) on relative abundances
#
# Inputs (generated by scripts/03_fungi_analysis.R):
#   outputs/objects/fungi_meta.rds
#   outputs/objects/fungi_matrix_counts.rds
#
# Outputs (not tracked by git; outputs/ is ignored):
#   outputs/figures/supplementary/FigS4_N_vs_Alpha_Fungi.pdf
#   outputs/figures/supplementary/FigS5_Alpha_Boxplots_Fungi.pdf
#   outputs/figures/supplementary/FigS6_PCoA_BrayCurtis_Fungi.pdf
# ======================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(vegan)
  library(patchwork)
})

dir.create("outputs/figures/supplementary", recursive = TRUE, showWarnings = FALSE)

# ---- Load saved objects ----
meta <- readRDS("outputs/objects/fungi_meta.rds")
X_counts <- readRDS("outputs/objects/fungi_matrix_counts.rds")

# Ensure alpha metrics exist (compute if needed)
if (!("Richness" %in% names(meta))) meta$Richness <- vegan::specnumber(X_counts)
if (!("Shannon"  %in% names(meta))) meta$Shannon  <- vegan::diversity(X_counts, index = "shannon")

# Consistent organ palette
organ_cols <- c(
  Bark  = "#E69F00",
  Grape = "#56B4E9",
  Leaf  = "#009E73",
  Soil  = "#0072B2"
)

# ======================================================================
# FIG S1 — N vs alpha diversity
# ======================================================================

p_N_rich <- ggplot(meta, aes(x = N, y = Richness)) +
  geom_point(aes(color = Organ), size = 2.4, alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linewidth = 0.6) +
  scale_color_manual(values = organ_cols) +
  labs(x = "Isolation success (N)", y = "Observed richness (classes)") +
  theme_classic(base_family = "Times New Roman", base_size = 12)

p_N_shan <- ggplot(meta, aes(x = N, y = Shannon)) +
  geom_point(aes(color = Organ), size = 2.4, alpha = 0.6,
             position = position_jitter(width = 0.15, height = 0.05)) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linewidth = 0.6) +
  scale_color_manual(values = organ_cols) +
  labs(x = "Isolation success (N)", y = "Shannon index") +
  theme_classic(base_family = "Times New Roman", base_size = 12)

p_S1 <- p_N_rich + p_N_shan +
  plot_layout(ncol = 2, guides = "collect") &
  theme(legend.position = "bottom")

ggsave("outputs/figures/supplementary/FigS4_N_vs_Alpha_Fungi.pdf",
       p_S1, width = 10.2, height = 4.4, device = cairo_pdf)

# ======================================================================
# FIG S2 — Alpha diversity across organs (faceted by Management)
# ======================================================================

p_rich_org <- ggplot(meta, aes(x = Organ, y = Richness, color = Organ)) +
  geom_boxplot(outlier.shape = NA, width = 0.6, color = "black") +
  geom_jitter(width = 0.12, size = 2.0, alpha = 0.7) +
  facet_wrap(~Management, nrow = 1) +
  scale_color_manual(values = organ_cols) +
  labs(x = NULL, y = "Observed richness (classes)") +
  theme_classic(base_family = "Times New Roman", base_size = 12) +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(face = "bold")
  )

p_shan_org <- ggplot(meta, aes(x = Organ, y = Shannon, color = Organ)) +
  geom_boxplot(outlier.shape = NA, width = 0.6, color = "black") +
  geom_jitter(width = 0.12, size = 2.0, alpha = 0.7) +
  facet_wrap(~Management, nrow = 1) +
  scale_color_manual(values = organ_cols) +
  labs(x = NULL, y = "Shannon index") +
  theme_classic(base_family = "Times New Roman", base_size = 12) +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(face = "bold")
  )

p_S2 <- p_rich_org / p_shan_org + plot_layout(heights = c(1, 1))

ggsave("outputs/figures/supplementary/FigS5_Alpha_Boxplots_Fungi.pdf",
       p_S2, width = 10.2, height = 7.2, device = cairo_pdf)

# ======================================================================
# FIG S3 — PCoA Bray–Curtis (relative abundances)
# ======================================================================

keep <- meta$N > 0
X_nz <- X_counts[keep, , drop = FALSE]
meta_nz <- meta[keep, , drop = FALSE]

X_rel <- vegan::decostand(X_nz, method = "total")

dist_bray <- vegan::vegdist(X_rel, method = "bray")
stopifnot(!any(is.na(dist_bray)))

pcoa_bray <- cmdscale(dist_bray, k = 2, eig = TRUE)

eig <- pcoa_bray$eig
var1 <- 100 * eig[1] / sum(eig[eig > 0])
var2 <- 100 * eig[2] / sum(eig[eig > 0])

ord <- as.data.frame(pcoa_bray$points)
colnames(ord) <- c("PCoA1", "PCoA2")
ord <- dplyr::bind_cols(meta_nz, ord)

p_S3 <- ggplot(ord, aes(PCoA1, PCoA2, color = Organ, shape = Management)) +
  geom_point(size = 3, alpha = 0.85,
             position = position_jitter(width = 0.008, height = 0.008)) +
  scale_color_manual(values = organ_cols) +
  theme_classic(base_family = "Times New Roman", base_size = 12) +
  labs(
    x = paste0("PCoA1 (", round(var1, 1), "%)"),
    y = paste0("PCoA2 (", round(var2, 1), "%)"),
    color = "Organ",
    shape = "Management"
  ) +
  theme(axis.title = element_text(face = "bold"))

ggsave("outputs/figures/supplementary/FigS6_PCoA_BrayCurtis_Fungi.pdf",
       p_S3, width = 7.2, height = 5.2, device = cairo_pdf)

message("Supplementary fungi figures exported to outputs/figures/supplementary/")

